name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup Yarn
      run: make installyarn
    - name: Build the application
      run: make all
    - name: Test the application
      run: make test
